config/routes.rb
Rails.application.routes.draw do

  # Root path
  # root to: 'pages#home'
  root to: 'workshops#index'
  
  # Create routes for users
    # users     GET    /users(.:format)          users#index
    #           POST   /users(.:format)          users#create
    # new_user  GET    /users/new(.:format)      users#new
    # edit_user GET    /users/:id/edit(.:format) users#edit
    # user      GET    /users/:id(.:format)      users#show
    #           PATCH  /users/:id(.:format)      users#update
    #           PUT    /users/:id(.:format)      users#update
    #           DELETE /users/:id(.:format)      users#destroy
  resources :users

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create routes for workshops
  #   workshops   GET    /workshops(.:format)          workshops#index
  #               POST   /workshops(.:format)          workshops#create
  #  new_workshop GET    /workshops/new(.:format)      workshops#new
  # edit_workshop GET    /workshops/:id/edit(.:format) workshops#edit
  #      workshop GET    /workshops/:id(.:format)      workshops#show
  #               PATCH  /workshops/:id(.:format)      workshops#update
  #               PUT    /workshops/:id(.:format)      workshops#update
  #               DELETE /workshops/:id(.:format)      workshops#destroy
  resources :workshops

  get '/workshops/:id/clone' => 'workshops#clone', as: 'clone_workshop'
  get '/workshops/:id/tasks' => 'workshops#edit_tasks', as: 'edit_workshop_tasks'

  # Create routes for tasks
  #     tasks GET    /tasks(.:format)              tasks#index
  #           POST   /tasks(.:format)              tasks#create
  #  new_task GET    /tasks/new(.:format)          tasks#new
  # edit_task GET    /tasks/:id/edit(.:format)     tasks#edit
  #      task GET    /tasks/:id(.:format)          tasks#show
  #           PATCH  /tasks/:id(.:format)          tasks#update
  #           PUT    /tasks/:id(.:format)          tasks#update
  #           DELETE /tasks/:id(.:format)          tasks#destroy
  resources :tasks
end

app/models/workshop.rb
class Workshop < ApplicationRecord

    # Relationships
    belongs_to :user, optional: true
    has_many :tasks
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]

  # CREATE
  def new
    @workshop = Workshop.new
  end # new

  def create
    workshop = Workshop.new workshop_params
    # Set signed in user as workshop creator
    workshop.user_id = @current_user.id
    workshop.save
    redirect_to workshop_path(workshop.id)
  end # create

  # READ
  def index
    if @current_user.present?
      @workshops_personal = Workshop.where(user_id: @current_user.id) 
      @templates = Workshop.where(user_id: nil) 
      other_users_workshops = Workshop.where.not(user_id: @current_user.id) and Workshop.where.not(user_id: nil)
      @workshops_public = other_users_workshops.where(private: false)
    else
      @templates = Workshop.where(user_id: nil) 
      other_users_workshops = Workshop.where.not(user_id: nil)
      @workshops_public = other_users_workshops.where(private: false)
    end # if
  end # index

  def show
    @workshop = Workshop.find params[:id]
    @workshop_time = seconds_to_string(@workshop.total_time) unless @workshop.total_time == nil
  end # show
  
  # UPDATE
  def edit
    @workshop = Workshop.find params[:id]
    # Prevent user from editing workshop if they did not create it
    redirect_to login_path unless @workshop.user.id == @current_user.id
  end # edit
  
  def update
    workshop = Workshop.find params[:id]
    
    # Prevent edit from being committed unless it is the user who created the task
    redirect_to login_path and return unless workshop.user_id == @current_user.id

    workshop.update workshop_params
    redirect_to workshop_path(workshop.id)
  end # update

  def edit_tasks
    @workshop = Workshop.find params[:id]
    @personal_tasks = Task.where(user_id: @current_user.id)
    @template_tasks = Task.where(user_id: nil)
  end # edit_tasks

  # DELETE
  def destroy
    Workshop.destroy params[:id]
    redirect_to workshops_path
  end # destroy

  def clone
    # Retrieve the workshop the user wants to clone
    original_workshop = Workshop.find params[:id]

    # Clone the workshop using duplicate
    clone_workshop = original_workshop.dup

    # Assign the clone to the current user
    clone_workshop.user_id = @current_user.id
    
    # Loop through the original workshops tasks
    original_workshop.tasks.each do |task|
      # Duplicate task
      clone_task = task.dup
      # Set user id to current user
      clone_task.user_id = @current_user.id
      # Set workshop id to clone_workshop.id
      clone_task.workshop = clone_workshop
      # Commit to database
      clone_task.save
    end

    # Commit to the database
    clone_workshop.save

    # Show workshop -> Created by should be current user instead of original creator
    redirect_to workshop_path(clone_workshop.id)
  end

  private

  def workshop_params
    params.require(:workshop).permit(:title, :description, :private, {task_ids: []})
  end # workshop_params
end # WorkshopsController

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_with model: @workshop, local: true do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <br>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <br>
    <br>
    <%= f.label :private, 'Would you like to make it private?' %>
    <br>
    <br>
    <div class="radio-button">
        <%= f.radio_button :private, true, :checked => true, :value => true %>
        <%= f.label :private, 'Private', value: true %>
        <br>
        <%= f.radio_button :private, false, :value => false %>
        <%= f.label :private, 'Public', value: false %>
    </div>
    <br>
    <%= f.submit :class => 'primary-button button-link'%>
<% end %>

app/views/workshops/edit_tasks.html.erb
<br>
<br>
<div class="workshops">
  <h2>Add tasks to <%= @workshop.title %></h2>
  <br>
  <%= form_for @workshop do |f| %>
  <%# Display check boxes for all tasks and pre-select any already associated with the workshop %>
      <div class="task-section-heading">
        <h2>My tasks</h2>
      </div>
    <br>
    <ul class="checkbox-group">
      <%= f.collection_check_boxes(:task_ids, @personal_tasks, :id, :task_details) do |b| %>
        <li><%= b.label class: "checkbox-label" do%>
          <%= b.check_box %>
        <span class="checkbox-text"><%= b.text %></span>
        <% end %></li>
      <% end %>
          <li class="filling-empty-space-childs"></li>
          <li class="filling-empty-space-childs"></li>
    </ul>

    <br>
    <div class="task-section-heading">
      <h2>Suggested tasks</h2>
    </div>
    <br>
    <ul class="checkbox-group">
    <%= f.collection_check_boxes(:task_ids, @template_tasks, :id, :task_details) do |b| %>
      <li><%= b.label class: "checkbox-label" do%>
        <%= b.check_box %>
      <span class="checkbox-text"><%= b.text %></span>
      <% end %></li>
    <% end %>
              <li class="filling-empty-space-childs"></li>
          <li class="filling-empty-space-childs"></li>
    </ul>
    <br>

    <%= f.submit  class: "primary-button submit-button" %>
  <% end %>

  <%= link_to 'Create a task', new_task_path %>
</div>

app/views/workshops/index.html.erb
<div class="workshops">
<% if @current_user.present? %>
    <div class="section-heading">
        <h2>My workshops</h2>
    </div>
    <ul class="tile-group">
        <li>
            <%= link_to new_workshop_path, class: "workshop-tile new-workshop" do %>
                <div class="create-symbol">+</div>
                <p>Add a workshop</p>
            <% end %>
        </li>
        <% @workshops_personal.each do |workshop| %>
            <li>
                <%= link_to workshop_path(workshop.id), class: "workshop-tile"  do %>
                    <strong><%= workshop.title %></strong>
                    <p><%= workshop.description %></p>
                <% end %>
            </li>
        <% end %>
        <li class="filling-empty-space-childs"></li>
        <li class="filling-empty-space-childs"></li>
    </ul>
    <br>
<% end %>
<div class="section-heading">
    <h2>Suggested workshops</h2>
</div>
<ul class="tile-group">
    <% @templates.each do |workshop| %>
        <li>
            <%= link_to workshop_path(workshop.id), class: "workshop-tile"  do %>
                <strong><%= workshop.title %></strong>
                <p><%= workshop.description %></p>
            <% end %>
        </li>
    <% end %>
    <li class="filling-empty-space-childs"></li>
    <li class="filling-empty-space-childs"></li>
</ul>
<br>
<% if @workshops_public.present? %>
<div class="section-heading">
    <h2>Workshops created by others</h2>
</div>
<ul class="tile-group">
    <% @workshops_public.each do |workshop| %>
        <li>
            <%= link_to workshop_path(workshop.id), class: "workshop-tile"  do %>
                <strong><%= workshop.title %></strong>
                <p><%= workshop.description %></p>
            <% end %>
        </li>
    <% end %>
    <li class="filling-empty-space-childs"></li>
    <li class="filling-empty-space-childs"></li>
</ul>
<% end %>
</div>
</div>

app/views/workshops/new.html.erb
<%= render partial: 'form' %>

app/views/workshops/show.html.erb
<article class="workshop">
   <header class="workshop-description">
      <h2><%= @workshop.title %></h2>
   </header>
   <br>
   <section class="task-list">
      <ul>
         <% @workshop.tasks.each do |task| %>
         <li>
            <span class="task-details">
            <%= link_to task.title, task_path(task.id) %>
            <%= seconds_to_string(task.time) unless task.time == nil %>
            </span>
            <span class="description"><%= task.description%></span>
         </li>
      <% end %>
      <%# Display total time %>
      <% if @workshop_time.present? %>
      <li>
         <span class="task-details">
            <p>Total time</p>
            <%= @workshop_time %>
         </span>
      </li>
      <% end %>
      </ul>
   </section>
   <nav aria-label="Workshop menu">
      <ul>
      <%# Only the creator of the workshop can edit/delete/add tasks%>
      <% if @current_user.present? %>
         <% if @current_user == @workshop.user %>
            <li><%= link_to 'Add or Remove Tasks', edit_workshop_tasks_path %></li>
            <li><%= link_to 'Edit', edit_workshop_path(@workshop.id) %></li>
            <li><%= link_to 'Delete', workshop_path(@workshop.id), method: 'delete' %></li>
         <% else %>
         <%# User must be signed in to clone a workshop%>
            <li><%= link_to 'Clone workshop', clone_workshop_path %></li>
         <% end %>
      <% end %>
      </ul>
   </nav>
</article>