config/routes.rb
Rails.application.routes.draw do

  # Root path
  # root to: 'pages#home'
  root to: 'workshops#index'
  
  # Create routes for users
    # users     GET    /users(.:format)          users#index
    #           POST   /users(.:format)          users#create
    # new_user  GET    /users/new(.:format)      users#new
    # edit_user GET    /users/:id/edit(.:format) users#edit
    # user      GET    /users/:id(.:format)      users#show
    #           PATCH  /users/:id(.:format)      users#update
    #           PUT    /users/:id(.:format)      users#update
    #           DELETE /users/:id(.:format)      users#destroy
  resources :users

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create routes for workshops
  #   workshops   GET    /workshops(.:format)          workshops#index
  #               POST   /workshops(.:format)          workshops#create
  #  new_workshop GET    /workshops/new(.:format)      workshops#new
  # edit_workshop GET    /workshops/:id/edit(.:format) workshops#edit
  #      workshop GET    /workshops/:id(.:format)      workshops#show
  #               PATCH  /workshops/:id(.:format)      workshops#update
  #               PUT    /workshops/:id(.:format)      workshops#update
  #               DELETE /workshops/:id(.:format)      workshops#destroy
  resources :workshops

  get '/workshops/:id/clone' => 'workshops#clone', as: 'clone_workshop'
  get '/workshops/:id/tasks' => 'workshops#edit_tasks', as: 'edit_workshop_tasks'

  # Create routes for tasks
  #     tasks GET    /tasks(.:format)              tasks#index
  #           POST   /tasks(.:format)              tasks#create
  #  new_task GET    /tasks/new(.:format)          tasks#new
  # edit_task GET    /tasks/:id/edit(.:format)     tasks#edit
  #      task GET    /tasks/:id(.:format)          tasks#show
  #           PATCH  /tasks/:id(.:format)          tasks#update
  #           PUT    /tasks/:id(.:format)          tasks#update
  #           DELETE /tasks/:id(.:format)          tasks#destroy
  resources :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    #Relationships
    belongs_to :user, optional: true
    belongs_to :workshop, optional: true

    # Information displayed about a task when adding a task to a workshop
    def task_details
        "#{title}"
    end # task_details
end # Task

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]

  # CREATE
  def new
    @task = Task.new
  end # new

  def create
    task = Task.new task_params
    # Set signed in user as task creator
    task.user_id = @current_user.id
    task.save
    redirect_to task_path(task.id)
  end # create

  # READ
  def index
    @tasks = Task.all
  end # index

  def show
    @task = Task.find params[:id]
    @task_time = seconds_to_string @task.time
  end # show

  # UPDATE
  def edit
    @task = Task.find params[:id]
    # Prevent user from accessing edit functionality if they did not create the task
    redirect_to login_path unless @task.user == @current_user
  end # edit

  def update
    task = Task.find params[:id]

    # Prevent the edit from being committed unless it is the user who created the task
    redirect_to login_path and return unless task.user_id == @current_user.id

    task.update task_params
    redirect_to task_path(task.id)
  end # update

  # DELETE
  def destroy
    Task.destroy params[:id]
    redirect_to tasks_path
  end # destroy

  private

  def task_params
    params.require(:task).permit(:title, :description, :tools, :time, :num_participants, :private)
  end # task_params
end # TasksController

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <br>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <br>
    <%= f.label :tools %><br>
    <%= f.text_field :tools %>
    <br>
    <%= f.label :time, 'How long is the workshop?' %><br>
    <%= f.number_field :time %>
    <br>
    <%= f.label :num_participants, 'How many participants?' %><br>
    <%= f.number_field :num_participants%>
    <br>
    <%= f.label :private, 'Would you like to make it private?' %>
    <br>
    <br>
    <div class="radio-button">
        <%= f.radio_button :private, true, :checked => true, :value => true %>
        <%= f.label :private, 'Private', value: true %>
        <br>
        <%= f.radio_button :private, false, :value => false %>
        <%= f.label :private, 'Public', value: false %>
    </div>
    <br>
    <%= f.submit class: 'primary-button' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render partial: 'form' %>

app/views/tasks/index.html.erb
<h2>Tasks</h2>
<ul>
<% @tasks.each do |task| %>
<li>
<%= link_to  task.title, task_path(task.id) %>
</li>
<% end %>
</ul>
<%= link_to 'Create a task', new_task_path %>

app/views/tasks/new.html.erb
<%= render partial: 'form' %>

app/views/tasks/show.html.erb
    <br>
    <div class="task-section-heading">
   <h2>Task: <%= @task.title %></h2>
   </div>
   <br>
<div class="task-summary">
   <strong>Description</strong>
   <p><%= @task.description %></p>
   <br>
   <strong>Number of participants:</strong>
   <p><%= @task.num_participants.to_s %></p>
   <br>
   <strong>Tools:</strong>
   <p><%= @task.tools %></p>
   <br>
   <strong>Duration:</strong>
   <p><%= @task_time %></p>
   <br>
   <% if @task.user.present?%>
      <strong>Created by:</strong> 
      <p><%= @task.user.username %></p>
   <% end %>
   <br>
   <strong><small>Availability:</small></strong>
   <% if @task.private %>
      <small>Private, only you can view this task.</small>
   <% else %>
      <small>Public, anyone can view or clone this task</small>
   <% end %>
</div>
<nav aria-label="Task menu">
<ul>
   <li><%= link_to "Back to #{@task.workshop.title}", workshop_path(@task.workshop_id) unless @task.workshop_id.nil? %></li>

   <li><%= link_to 'Edit', edit_task_path(@task.id) %></li>
   <li><%= link_to 'Delete', task_path(@task.id), method: 'delete' %></li>
   </ul>
</nav>